[project]
name = "anki-type-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anki>=25.2.1",
    "aqt>=25.2.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.399",
    "ruff>=0.11.6",
]
